package common;

import java.io.Serializable;

/**
 * @author Gabriel
 * @since November 20th
 * @version 1.3 {@summary } Serializable object used to simulate a Traffic Light.
 */
public class TrafficLight implements Serializable {
	/**
	 * Generated by Eclipse attribute. Not sure how its used, maybe internally?
	 */
	private static final long serialVersionUID = -3959879361239673620L;

	/**
	 * {@summary } Attribute used to define object's state. By default in a ENTER state so object is never null.
	 */
	TrafficLightStates state = TrafficLightStates.ENTER;

	/**
	 * {@summary } Default constructor sets state to Green.
	 */
	public TrafficLight() {
		setState(TrafficLightStates.GREEN);
	}

	/**
	 * {@summary } Default setter, changed its access to private since its only used internally.
	 * 
	 * @param state
	 * @return this object
	 */
	private TrafficLight setState(TrafficLightStates state) {
		this.state = state;
		return this;
	}

	/**
	 * Default getter
	 * 
	 * @return
	 */
	public TrafficLightStates getState() {
		return state;
	}

	/**
	 * {@summary } Method to visualize object's state as String, as of Version 1.3 mostly used for debugging.
	 */
	@Override
	public String toString() {
		switch (getState()) {
		case ENTER:
			return "Enter";
		case RED:
			return "Red";
		case YELLOW:
			return "Yellow";
		case GREEN:
			return "Green";
		case EXIT:
			return "Exit";
		}
		return null;
	}

	/**
	 * {@summary } Method used to transition between states as they only travel in one direction.
	 */
	public void nextState() {
		if (this.state == TrafficLightStates.GREEN)
			setState(TrafficLightStates.YELLOW);
		else if (this.state == TrafficLightStates.YELLOW)
			setState(TrafficLightStates.RED);
		else if (this.state == TrafficLightStates.RED)
			setState(TrafficLightStates.GREEN);
	}

}
